version: "3.9"

services:
  backend1:
    build:
      dockerfile: Dockerfile
      context: .
    image: goback
    container_name: app1
    depends_on:
      - postgres
      - migrate
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    networks:
        - dev

  backend2:
    image: goback
    container_name: app2
    depends_on:
      - postgres
      - backend3
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    networks:
      - dev

  backend3:
    image: goback
    container_name: app3
    depends_on:
      - postgres
      - backend1
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    networks:
      - dev
  
  postgres:
    image: postgres:12.19-bullseye
    container_name: postgres-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/postgres.conf:/usr/local/etc/postgres/postgres.conf
      - ./postgres/postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
        reservations:
          cpus: '0.2'
          memory: 512M
    networks:
        - dev

  postgres-test:
    image: postgres:12.19-bullseye
    container_name: postgres-test-db
    environment:
      POSTGRES_DB: test-db
      POSTGRES_USER: test-user
      POSTGRES_PASSWORD: test-password
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - "5431:5432"
    volumes:
      - ./postgres/test-postgres.conf:/usr/local/etc/postgres/postgres.conf
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test-user -d test-db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 512M
    networks:
      - dev

  nginx:
    build:
      dockerfile: NginxDockerfile
      context: ./nginx
    depends_on:
      - backend1
      - backend2
      - backend3
    ports:
      - "80:80"
    restart: always
    networks:
      - dev

  migrate:
    build:
      dockerfile: Dockerfile
      context: ./migrations
    depends_on:
      - postgres
    volumes:
      - migrations:/migrations
    entrypoint: [ "migrate", "-path", "/migrations", "-database", "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?sslmode=disable", "up" ]
    networks:
        - dev

volumes:
  postgres:
  migrations:
  
networks:
    dev: 
        driver: bridge
