name: Build Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run:
          docker build -t goback .

      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Run services
        run:
          docker-compose up -d

      - name: Check services
        run:
          sleep 10
          docker-compose ps -a

      - name: Stop services
        run:
          docker-compose down
