name: Build Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment: avito-env

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Run services
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
          REDIS_LOG_LEVEL: ${{ vars.REDIS_LOG_LEVEL }}
        run: |
          export POSTGRES_USER=$POSTGRES_USER POSTGRES_PASSWORD=$POSTGRES_PASSWORD POSTGRES_DB=$POSTGRES_DB
          docker-compose up -d
          docker logs postgres-db
          

      - name: Check services
        run: |
          sleep 10
          docker-compose ps

      - name: Test
        run:
          cd tests
          go test .

      - name: Stop services
        run:
          docker-compose down